config/routes.rb
Rails.application.routes.draw do
 
  root to: "pages#home"

  # get 'search', to: 'search#index'
  resources :cars do
    resources :car_orders, only: [:create]
    resource :saved_cars, only: [:create, :destroy], controller: "saved_cars"
  end
  resources :car_orders, only: [:index]
  resources :saved_cars, only: [:index]
  resources :engines do
    resources :engine_orders, only: [:new, :create]
    resource :saved_engines, only: [:create, :destroy], controller: "saved_engines"
  end
  resources :car_engines
  resources :engine_orders, only: [:index]
  resources :reviews, only: [ :index, :show ]
  devise_for :users

 

  resources :carts do 
    scope module: :carts do 
      resources :purchases, only: [:new, :create] do 
        get :success, on: :collection
      end
      resources :stripe_checkouts, only: [ :create]
    end
  end
 get "cart/checkout", to: "carts#checkout"

  get '/audi', to: 'pages#audi'
  get '/bmw', to: 'pages#bmw'
  get '/ford', to: 'pages#ford'
  get '/nissan', to: 'pages#nissan'
  get '/peugeot', to: 'pages#peugeot'
  get '/toyota', to: 'pages#toyota'
  get '/volkswagen', to: 'pages#volkswagen'
  get '/mercedes', to: 'pages#mercedes'
  get '/carorders/:id/confirmation', to: 'car_orders#confirmation', as: 'order_confirmation'
  get 'engineorders/:id/confirmation', to: 'engine_orders#confirmation', as: 'engine_order_confirmation'
  get '/faq', to: 'pages#faq'
  get 'feed/google', to: 'feed#google', defaults: { format: 'xml' }
  get '/about-us', to: 'pages#about_us' 
  get '/warranty', to: 'pages#warranty' 
  get '/privacy-policy', to: 'pages#privacy_policy'
  get '/shipping-policy', to: 'pages#shipping_policy'
  get '/returns-and-refund', to: 'pages#returns_policy'
  get '/contact-us', to: 'pages#contact'

  # routes for the controller
  # resources :orders, only: [:create, :index ]
  # get "orders/success", to: "orders#success"
  # get "orders/cancel", to: "orders#cancel"
  post "cart/add_item", to: "carts#add_item"
  post "cart/remove/:id", to: "carts#remove_item", as: :cart_remove_item
  get "cart/checkout", to: "carts#checkout"

  # resource :cart, only: [:show] do
  #   post "add_item", to: "carts#add_item"
  #   post "remove_item/:id", to: "carts#remove_item", as: "remove_item"
  #   get "checkout", to: "carts#checkout"
  # end


  # resources :carts, only: [:show] do
  #   member do
  #     post "add_item/:engine_id", to: "carts#add_item", as: :add_item
  #     delete "remove_item/:engine_id", to: "carts#remove_item", as: :remove_item
  #   end
  # end

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/engine.rb
class Engine < ApplicationRecord
  

  # handles he slugs for friendly domain
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
    [
      :title,
      [:title, :manufacturer]
    ]
  end
  def manufacturer
    engineable.try(:manufacturer)
  end

  #handles associations
  belongs_to :engineable, polymorphic: true
  has_many :engine_orders, dependent: :destroy

  

  
  has_many :carts, through: :line_items

  accepts_nested_attributes_for :engineable

  #performs general search in the pg database
  include PgSearch::Model
  pg_search_scope :search_by_details,
    against: [:title, :engineable_type, :description],
    using: {
      tsearch: { prefix: true } # Allows partial matches (e.g., "Hon" matches "Honda")
    }
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    # Start with the Engine model, eager load engineable associations
    @engines = Engine.includes(:engineable)

    # Apply search if a query is present
    if params[:query].present?
      @engines = @engines.search_by_details(params[:query])
    end

    # Apply filters
    @engines = filter_engines(@engines, params)

    # Apply pagination to the final filtered/queried results
    @paginated_items = @engines.order(created_at: :desc).page(params[:page]).per(15)
  end


  def show
    @engine = Engine.friendly.find(params[:id])
    @order = EngineOrder.new(engine: @engine)
  end

  def new
    @car_engine = CarEngine.new
    @car_engine.build_engine
  end

  def create
    @car_engine = CarEngine.new(car_engine_params)
    if @car_engine.save
      redirect_to @car_engine, notice: 'Car engine created successfully.'
    else
      render :new
    end
  end

  def edit
    @engine = Engine.friendly.find(params[:id])
    @engine.build_engineable if @engine.engineable.nil?
  end


  def update
    @engine = Engine.friendly.find(params[:id])

    # Attach photos to the engineable (CarEngine)
    if params[:engine][:photos].present?
      @engine.engineable.photos.purge # ⬅️ Delete old photos
      params[:engine][:photos].each do |photo|
        @engine.engineable.photos.attach(photo)
      end
    end

    if @engine.update(engine_params.except(:photos))
      redirect_to @engine, notice: 'Car engine updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @engine = Engine.friendly.find(params[:id])
    @engine.destroy
  end
  private

  def engine_params
    params.require(:engine).permit(
      :title,
      :price,
      :description,
      :slug,
      photos: [], # allow multiple uploads
      engineable_attributes: [
        :id,
        :horsepower,
        :fuel_type,
        :transmission,
        :mileage,
        :manufacturer,
        :year,
        :condition,
        :description
      ]
    )
  end


  def filter_engines(engines, params)
    # Filter by Engine Type
    if params[:engine_type].present?
      engines = engines.where(engineable_type: params[:engine_type])
    end

    # Filter by Price Range
    if params[:min_price].present? && params[:max_price].present?
      engines = engines.where(price: params[:min_price]..params[:max_price])
    end

    # Filter Specific Attributes Based on Type
    case params[:engine_type]
    when "CarEngine"
      engines = engines.joins("JOIN car_engines ON car_engines.id = engines.engineable_id")
      engines = engines.where("car_engines.horsepower >= ?", params[:min_hp]) if params[:min_hp].present?
      engines = engines.where("car_engines.fuel_type = ?", params[:fuel_type]) if params[:fuel_type].present?
    when "TruckEngine"
      engines = engines.joins("JOIN truck_engines ON truck_engines.id = engines.engineable_id")
      engines = engines.where("truck_engines.towing_capacity >= ?", params[:min_towing]) if params[:min_towing].present?
    when "BoatEngine"
      engines = engines.joins("JOIN boat_engines ON boat_engines.id = engines.engineable_id")
      engines = engines.where("boat_engines.power >= ?", params[:min_power]) if params[:min_power].present?
    end

    engines
  end


end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/edit.html.erb
<h1>Edit Car Engine</h1>

<%= form_with(model: @engine, local: true, html: { class: "engine-form" }) do |f| %>
  <% if @engine.errors.any? %>
    <div class="error-messages">
      <h2><%= pluralize(@engine.errors.count, "error") %> prevented saving:</h2>
      <ul>
        <% @engine.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <!-- Engine fields -->
  <h2>Engine Metadata</h2>
  <%= f.fields_for :engine do |e| %>
    <div class="form-lines"><%= e.label :title %><br><%= e.text_field :title %></div>
    <div class="d-none"><%= e.label :price %><br><%= e.number_field :price, step: 0.01 %></div>
    <div class="d-none"><%= e.label :description %><br><%= e.text_area :description %></div>
    <div class="d-none"><%= e.label :slug %><br><%= e.text_field :slug %></div>
    <%= e.hidden_field :id %>
  <% end %>

  <!-- CarEngine fields -->
  <%= f.fields_for :engineable do |c| %>
   
    <h2>Car Engine Details</h2>
    <div class="form-lines"><%= c.label :horsepower %><br><%= c.number_field :horsepower %></div>
    <div class="form-lines"><%= c.label :fuel_type %><br><%= c.text_field :fuel_type %></div>
    <div class="form-lines"><%= c.label :transmission %><br><%= c.text_field :transmission %></div>
    <div class="form-lines"><%= c.label :mileage %><br><%= c.number_field :mileage %></div>
    <div class="form-lines"><%= c.label :manufacturer %><br><%= c.text_field :manufacturer %></div>
    <div class="form-lines"><%= c.label :year %><br><%= c.text_field :year %></div>
    <div class="form-lines"><%= c.label :price %><br><%= c.number_field :price, step: 0.01 %></div>
    <div class="form-lines"><%= c.label :condition %><br><%= c.text_field :condition %></div>
    <div class="form-lines"><%= c.label :description %><br><%= c.text_area :description %></div>

    <h2>Photos</h2>
    <% if @engine.engineable.photos.attached? %>
        <div class="photo-previews">
        <% @engine.engineable.photos.each do |photo| %>
            <%= image_tag photo, alt: "Car photo", class: "edit-thumbnail" %>
        <% end %>
        </div>
    <% end %>
    <div class="form-lines">
        <%= c.label :photos, "Upload New Photos" %><br>
        <%= f.file_field :photos, multiple: true, direct_upload: true %>
    </div>
    <% end %>
  
  <%= f.submit "Update Car Engine", class: "submit-button" %>
<% end %>

app/views/engines/index.html.erb
<% content_for :title, "Engines for Sale - Find New & Used Car Engines" %>
<% content_for :meta_description, "Shop high-quality car engines for sale, including petrol, diesel, hybrid, and electric engines. Get the best deals on powerful and fuel-efficient engines!" %>
<% content_for :meta_keywords, "car engines, engines for sale, used engines, new engines, V8 engine, diesel engine, hybrid engine, performance engines" %>

<% content_for :meta_og_title, "Engines for Sale - Best Deals on Car Engines" %>
<% content_for :meta_og_description, "Browse a wide selection of high-quality petrol, diesel, hybrid, and electric engines. Find the perfect engine for your vehicle today!" %>
<% content_for :meta_og_image, "https://res.cloudinary.com/drxr1eiwp/image/upload/v1735304802/s-l1600_2_pgnwbn.webp" %>


<div class="content-wrapper">
  <div class="makes-section">
    <%= render "shared/index_engine_filter" %>
  </div>
  <div class="main-content">
    <div class="engines">
        <% if  @paginated_items.any? %>
          <% @paginated_items.each do |engine| %>
          <div class="card">
              <%= link_to engine_path(engine) do %>
                <% if engine.engineable.present? && engine.engineable.photos.any? %>
                  <%= image_tag engine.engineable.photos.first, alt: engine.title, height: 250, width: 300, class: "engine-image" %>
                <% else %>
                  <div style="height: 250px; width: 300px; display: flex; align-items: center; justify-content: center; background: #eee;">
                    <span>Deleted or no photos</span>
                  </div>
                <% end %>
              <% end %>

              <div class="card-info">
                <%= link_to engine_path(engine), style: "text-decoration: none;" do %>
                  <h4><%= engine.title %></h4>
                  <p class="price">Price: <%= number_to_currency(engine.price > 3000 ? engine.price - 2770 : engine.price) %></p>
                <% end %>
               
              <% if engine.engineable.is_a?(CarEngine) || engine.engineable.is_a?(TruckEngine) %>
                  <p>
                    <i class="fas fa-tachometer-alt"></i>
                    Millage: <%= engine.engineable.mileage %> Mi
                  </p>
                   <%= form_with url: cart_add_item_path, method: :post, data: { turbo: true } do |f| %>
                      <%= hidden_field_tag :engine_id, engine.id %>
                      <div class="d-none"><%= f.number_field :quantity, value: 1, min: 1 %></div>
                      <%= f.submit "Add to Cart", class: "btn btn-primary" %>
                    <% end %>
                <% else %>
                  <p>
                    <i class="fas fa-bolt"></i>
                    Power: <%= engine.engineable.power %> HP
                  </p>
                  
                  <%= form_with url: cart_add_item_path, method: :post, data: { turbo: true } do |f| %>
                    <%= hidden_field_tag :engine_id, engine.id %>
                    <div class="d-none"><%= f.number_field :quantity, value: 1, min: 1 %></div>
                    <%= f.submit "Add to Cart", class: "btn btn-primary" %>
                  <% end %>
                <% end %>

              </div>
            </div>
          <% end %>
          <% else %>
            <div style="margin: 30px;">
              <h1>Search Results</h1>
              <p>It seems we can't find an engines with name: <strong style="text-decoration: underline; font-size: 1.1rem;"> <%= params[:query]%></strong></p>
            </div>
          <% end %>
      </div>
      <div class="pagination-container">
        <%= paginate @paginated_items %>
      </div>
    </div>
  </div>

</div>
<div class="used-car-promo">
    <div class="promo-content">
        <h2>Find Your Perfect Engine with AutoBidSeller</h2>
        <p>
            Whether you're restoring a classic car, upgrading your truck, or repowering your boat,
            AutoBidSeller offers a diverse selection of used and rebuilt engines.
            Find reliable performance at competitive prices, backed by our commitment to quality.
        </p>
        <ul>
            <li><strong>Wide Selection:</strong> Discover engines for cars, trucks, and boats.</li>
            <li><strong>Quality Assurance:</strong> Rigorous inspection and testing of all engines.</li>
            <li><strong>Competitive Prices:</strong> Get the best value for your investment.</li>
            <li><strong>Expert Support:</strong> Our team is ready to help you find the right engine.</li>
        </ul>
        <%= link_to "Explore Engines", engines_path, class: "btn-cta" %>
    </div>
    <div class="promo-image">
        <%= image_tag "pablo.jpg", alt: "Illustration of a happy family with a used car", style: "max-height: 500px" %>
    </div>
</div>

app/views/engines/new.html.erb
<h1 class="text-center">Engines#new</h1>
<%= form_with(model: @car_engine, local: true, html: { multipart: true, class: "engine-form" }) do |f| %>
  <div class="form-lines"><%= f.label :horsepower %><br><%= f.number_field :horsepower %></div>
  <div class="form-lines"><%= f.label :fuel_type %><br><%= f.text_field :fuel_type %></div>
  <div class="form-lines"><%= f.label :transmission %><br><%= f.text_field :transmission %></div>
  <div class="form-lines"><%= f.label :mileage %><br><%= f.number_field :mileage %></div>
  <div class="form-lines"><%= f.label :manufacturer %><br><%= f.text_field :manufacturer %></div>
  <div class="form-lines"><%= f.label :year %><br><%= f.text_field :year %></div>
  <div class="form-lines"><%= f.label :price %><br><%= f.number_field :price, step: 0.01 %></div>
  <div class="form-lines"><%= f.label :condition %><br><%= f.text_field :condition %></div>
  <div class="form-lines"><%= f.label :description %><br><%= f.text_area :description %></div>

  <h2>Engine Metadata</h2>
  <%= f.fields_for :engine do |e| %>
    <div class="form-lines"><%= e.label :title %><br><%= e.text_field :title %></div>
    <div class="form-lines"><%= e.label :price %><br><%= e.number_field :price, step: 0.01 %></div>
    <div class="form-lines"><%= e.label :description %><br><%= e.text_area :description %></div>
    <div class="form-lines"><%= e.label :slug %><br><%= e.text_field :slug %></div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/engines/show.html.erb
<div class="bike-contain" data-controller="showcars">
  <div class="bike-main-content">
    <div class="bike-main-image">
      <% content_for :title, "#{@engine.title} for Sale | Latest Auto Events & Exhibitions" %>
      <% content_for :meta_description, @engine.engineable.description.truncate(156) %>
      <% content_for :meta_keywords, "engine for sale, #{@engine.title}, used #{@engine.title}, new #{@engine.title}, buy #{@engine.title} engine, performance engine" %>

      <% content_for :meta_og_title, "#{@engine.title} for Sale - Best Deals on #{@engine.title} Engines" %>
      <% content_for :meta_og_description, @engine.engineable.description.truncate(166) %>
      <% content_for :meta_og_image, cl_image_path(@engine.engineable.photos.first.key) %>

      <% if @engine.engineable.photos.attached? %>
        <% @engine.engineable.photos.each_with_index do |photo, index| %>
          <div class="mySlides" data-showcars-target="slide" style="<%= index == 0 ? '' : 'display:none;' %>">
            <div class="numbertext">
              <i class="fa-solid fa-camera"></i> <%= index + 1 %>/<%= @engine.engineable.photos.count %>
            </div>
            <%= cl_image_tag photo.key, alt: "#{@engine.title}", class: "main-image" %>
          </div>
        <% end %>
      <% end %>

      <!-- Navigation Buttons -->
      <div class="slider-nav">
        <a class="prev" data-action="click->showcars#prev">❮</a>
        <a class="next" data-action="click->showcars#next">❯</a>
      </div>

      <!-- Save Engine Button -->
      <div class="saved-bike">
        <% if user_signed_in? %>
          <% saved = current_user.saved_engines.exists?(engine: @engine) %>

          <%= button_to engine_saved_engines_path(@engine),
                        method: saved ? :delete : :post,
                        remote: true,
                        class: "btn favorite-btn",
                        data: { id: @engine.id } do %>
          <i class="<%= saved ? 'fa-solid fa-heart' : 'fa-regular fa-heart' %>"
            style="<%= saved ? 'color: red;' : '' %>"></i>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: "btn" do %>
            <i class="fa-regular fa-heart"></i>
          <% end %>
        <% end %>
      </div>

      <!-- Bike Gallery -->
      <div class="bike-gallery">
        <% if @engine.engineable.photos.attached? %>
          <div class="thumbnails">
            <% @engine.engineable.photos.each_with_index do |photo, index| %>
              <% next if index == 0 %><!-- Skip the first image -->
              <%= cl_image_tag photo.key,
                height: 100, width: 100, crop: :fill,
                class: "thumbnail",
                alt: "#{@engine.title}",
                data: { showcarsTarget: "thumbnail", action: "click->showcars#selectSlide", index: index + 1 } %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>




  <!-- Order Form Section -->
  <div class="bike-form">
      <div class="row m-2">
      <h2 style="font-family: 'Montserrat', sans-serif"><%= @engine.title %></h2>
      <h2 style="color: blue; font-size: 1.5rem; font-weight: 800;">
        <%= number_to_currency(@engine.price > 3000 ? @engine.price - 2770 : @engine.price) %>
      </h2>
    </div>

    <p style="font-weight: 700; text-align: center;"> PLACE A QUICK ORDER</p>
      
      <%= form_with url: cart_add_item_path, method: :post, data: { turbo: true }, class: "flex items-center gap-2" do %>
        <%= hidden_field_tag :engine_id, @engine.id %>
        <div class="d-none"><%= number_field_tag :quantity, 1, min: 1, class: "w-16 text-center border rounded" %></div>
        <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
      <% end %>

  <div data-controller="form-hide" >
    <button type="button" class="btn btn-dark" data-action="click->form-hide#toggle">Quick Enquiry</button>
    <div data-form-hide-target="form" class="hide-form">
      <%= simple_form_for [@engine, @order],
        local: true,
        data: { controller: "loading", action: "submit->loading#showSpinner" },
        html: { class: "custom-bike-form" } do |form| %>
        
        <% if @order.errors.any? %>
          <div class="error-messages alert alert-danger">
            <h3>There were some errors with your order:</h3>
            <ul>
              <% @order.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        <div class="form-group m-4">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group m-4">
          <%= form.label :email %>
          <%= form.email_field :email, class: "form-control" %>
        </div>

        <div class="form-group m-4">
          <%= form.label :phone %>
          <%= form.number_field :phone, class: "form-control" %>
        </div>

        <div class="form-group m-4">
          <%= form.label "Shipping address" %>
          <%= form.text_field :location, class: "form-control" %>
        </div>

        <div class="form-group submit-button m-4">
          <%= form.button :submit, "GET A PRICE QUOTE", class: "btn btn-dark text-white" %>
        </div>

        <!-- Hidden honeypot field (bots will try to fill this, humans won't) -->
        <%= form.hidden_field :extra_info, value: "", autocomplete: "off" %>
        <span class="loader text-center" data-loading-target="spinner" style="display: none;"></span>
      <% end %>
      </div>
  </div>
    <% if @engine.engineable_type == "CarEngine" %>
      <p style="margin-left: 1.0rem;">
        <td><strong>Compactibility: </strong></td>
        <td> <%= @engine.engineable.year %></td>
      </p>
      <p style="margin-left: 1.0rem;">
        <td><strong>Transmission: </strong></td>
        <td><%= @engine.engineable.transmission %></td>
      </p>
      <p style="margin-left: 1.0rem;">
        <td><strong>Engine Capacity: </strong></td>
        <td><i class="fa-solid fa-flag-checkered"></i> <%= @engine.engineable.horsepower %> cc</td>
      </p>
      <p style="margin-left: 1.0rem;">
        <td><strong>Fuel:</strong></td>
        <td><i class="fa-solid fa-gas-pump"></i> <%= @engine.engineable.fuel_type %></td>
      </p>
    <%end %>
  </div>
</div>

<!-- Bike Information Section -->
<div class="bike-details">
  <div class="popularity-stats">
    <%# <h2 class="stats-title"><i class="fa-solid fa-phone" style="color: green;"></i> Contact the Dealer (341)223-3974</h2> %>
    <div class="stats-row">
      <div class="stats-item">
        <i class="fa-solid fa-eye"></i>
        <span><strong>Seen:</strong> <%= rand(30..100) %> times (last 30 days)</span>
      </div>
      <div class="stats-item">
        <i class="fa-solid fa-bookmark"></i>
        <span><strong>Saved:</strong> by <%= rand(2..10) %> people</span>
      </div>
      <div class="stats-item">
        <i class="fa-solid fa-tags"></i>
        <span><strong>Price Update:</strong> The price recently decreased by $<%= rand(1000..5000) %></span>
      </div>
    </div>
  </div>

  <table class="mt-5">
    <tr>
      <td><strong>Condition:</strong></td>
      <td><%= @engine.engineable.condition %><strong></strong></td>
    <tr>
    <tr>
      <td><strong>Category:</strong></td>
      <td></i> <%= @engine.engineable_type %></td>
    </tr>
    <tr>
      <td><strong>Model:</strong></td>
      <td><i class="fa-solid fa-calendar"></i> <%= "#{@engine.engineable.year}" %> </td>
    </tr>
    <% if @engine.engineable_type == "BoatEngine" %>
      <tr>
        <td><strong>Engine Type:</strong></td>
        <td><i class="fa-solid fa-gauge-high"></i> <%= @engine.engineable.engine_type %></td>
      </tr>
      <% else%>
      <tr>
        <td><strong>Mileage:</strong></td>
        <td><i class="fa-solid fa-gauge-high"></i> <%= @engine.engineable.mileage %> km</td>
      </tr>
    <% end %>
    <% if @engine.engineable_type == "TruckEngine" %>
      <tr>
        <td><strong>Fuel:</strong></td>
        <td><i class="fa-solid fa-gas-pump"></i> <%= @engine.engineable.fuel_type %></td>
      </tr>
      <tr>
        <td><strong>Engine Capacity:</strong></td>
        <td><i class="fa-solid fa-flag-checkered"></i> <%= @engine.engineable.towing_capacity %> cc</td>
      </tr>
    <% end %>
    <% if @engine.engineable_type == "CarEngine" %>
      <tr>
        <td><strong>Transmission:</strong></td>
        <td><%= @engine.engineable.transmission %></td>
      </tr>
      <tr>
        <td><strong>Engine Capacity:</strong></td>
        <td><i class="fa-solid fa-flag-checkered"></i> <%= @engine.engineable.horsepower %> cc</td>
      </tr>
      <tr>
        <td><strong>Fuel:</strong></td>
        <td><i class="fa-solid fa-gas-pump"></i> <%= @engine.engineable.fuel_type %></td>
      </tr>
    <%end %>
    <tr>
      <td><strong>Manufacturer:</strong></td>
      <td><%= @engine.engineable.manufacturer %></td>
    </tr>
    <tr>
      <td><strong>Description:</strong></td>
      <td><%= @engine.description %></td>
    </tr>
    <tr>
      <td><strong>Situation</strong></td>
      <td>Used: An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used. See the seller's listing for full
         details and description of any imperfections.</td>
    <tr>
  </table>
  <div class="actions">
    <%= link_to "Explore More Engines", engines_path, class: "primary-btn" %>
  </div>

<div>
  <%= link_to engines_path, class: "back-link" do %>
    <i class="fas fa-arrow-left"></i> Back to Engines
  <% end %>

  <% if current_user&.admin? %>
  <%= link_to edit_engine_path(@engine), class: "btn btn-primary", style: "max-width: 300px;" do %>
    <i class="fas fa-edit"></i> Edit Engine
  <% end %>

  <%#= button_to engine_path(@engine), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary", style: "max-width: 300px;" do %>
    <%# <i class="fas fa-trash-alt"></i> Delete %>
  <%# end %>
<% end %>

</div>
</div>
</div>