config/routes.rb
Rails.application.routes.draw do
 
  root to: "pages#home"

  # get 'search', to: 'search#index'
  resources :cars do
    resources :car_orders, only: [:create]
    resource :saved_cars, only: [:create, :destroy], controller: "saved_cars"
  end
  resources :car_orders, only: [:index]
  resources :saved_cars, only: [:index]
  resources :engines do
    resources :engine_orders, only: [:new, :create]
    resource :saved_engines, only: [:create, :destroy], controller: "saved_engines"
  end
  resources :car_engines
  resources :engine_orders, only: [:index]
  resources :reviews, only: [ :index, :show ]
  devise_for :users

 

  resources :carts do 
    scope module: :carts do 
      resources :purchases, only: [:new, :create] do 
        get :success, on: :collection
      end
      resources :stripe_checkouts, only: [ :create]
    end
  end
 get "cart/checkout", to: "carts#checkout"

  get '/audi', to: 'pages#audi'
  get '/bmw', to: 'pages#bmw'
  get '/ford', to: 'pages#ford'
  get '/nissan', to: 'pages#nissan'
  get '/peugeot', to: 'pages#peugeot'
  get '/toyota', to: 'pages#toyota'
  get '/volkswagen', to: 'pages#volkswagen'
  get '/mercedes', to: 'pages#mercedes'
  get '/carorders/:id/confirmation', to: 'car_orders#confirmation', as: 'order_confirmation'
  get 'engineorders/:id/confirmation', to: 'engine_orders#confirmation', as: 'engine_order_confirmation'
  get '/faq', to: 'pages#faq'
  get 'feed/google', to: 'feed#google', defaults: { format: 'xml' }
  get '/about-us', to: 'pages#about_us' 
  get '/warranty', to: 'pages#warranty' 
  get '/privacy-policy', to: 'pages#privacy_policy'
  get '/shipping-policy', to: 'pages#shipping_policy'
  get '/returns-and-refund', to: 'pages#returns_policy'
  get '/contact-us', to: 'pages#contact'

  # routes for the controller
  # resources :orders, only: [:create, :index ]
  # get "orders/success", to: "orders#success"
  # get "orders/cancel", to: "orders#cancel"
  post "cart/add_item", to: "carts#add_item"
  post "cart/remove/:id", to: "carts#remove_item", as: :cart_remove_item
  get "cart/checkout", to: "carts#checkout"

  # resource :cart, only: [:show] do
  #   post "add_item", to: "carts#add_item"
  #   post "remove_item/:id", to: "carts#remove_item", as: "remove_item"
  #   get "checkout", to: "carts#checkout"
  # end


  # resources :carts, only: [:show] do
  #   member do
  #     post "add_item/:engine_id", to: "carts#add_item", as: :add_item
  #     delete "remove_item/:engine_id", to: "carts#remove_item", as: :remove_item
  #   end
  # end

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/car.rb
class Car < ApplicationRecord
  extend FriendlyId
  include PgSearch::Model
  friendly_id :slug_candidates, use: [:slugged, :finders]

  has_many :car_orders, dependent: :destroy
  has_many_attached :photos
  has_many :saved_cars, dependent: :destroy
  has_many :users, through: :saved_cars

  def slug_candidates
    "#{make}-#{model}-#{year}".parameterize
  end

  def should_generate_new_friendly_id?
    slug.blank? || make_changed? || model_changed? || year_changed?
  end
  pg_search_scope :search_by_details,
    against: [:make, :model, :year],
    using: {
      tsearch: { prefix: true } # Allows partial matches (e.g., "Hon" matches "Honda")
    }

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]
  def index
    # Static or Predefined Options
    @makes = Car.distinct.pluck(:make).uniq
    @models = Car.distinct.pluck(:model).uniq
    @steering_options = Car.distinct.pluck(:steering).uniq
    @years = Car.distinct.pluck(:year).uniq.sort.reverse
      set_meta_tags title: "Find New & Used Cars for Sale - AutoBidHub",
                    description: "Browse a massive selection of new and used cars from top brands like Toyota, BMW, Mercedes, Ford, and more. Find the best car deals today!",
                    keywords: "cars for sale, used cars, new cars, buy a car, affordable cars, best car deals, car marketplace"

    if filter_params_present?
      # Start with all cars and apply filters
      @paginated_items = Car.all
      @paginated_items = @paginated_items.where(make: params[:make]) if params[:make].present?
      @paginated_items = @paginated_items.where(model: params[:model]) if params[:model].present?
      @paginated_items = @paginated_items.where(steering: params[:steering]) if params[:steering].present?
      @paginated_items = @paginated_items.where("price >= ?", params[:min_price].to_f) if params[:min_price].present?
      @paginated_items = @paginated_items.where("price <= ?", params[:max_price].to_f) if params[:max_price].present?
      @paginated_items = @paginated_items.where(year: params[:year]) if params[:year].present?
      @paginated_items = @paginated_items.order(:make, :model).page(params[:page]).per(15)
    elsif params[:query].present?
      @paginated_items = Car.search_by_details(params[:query]).page(params[:page]).per(15)
    elsif params[:category].present?
      @paginated_items = Car.where(category: params[:category]).page(params[:page]).per(15)
    else
      @paginated_items = Car.page(params[:page]).order('RANDOM()').per(15)
    end

    @reviews = Review.order('RANDOM()').all
  end

  def show
    @car = Car.friendly.find(params[:id])
    @order = CarOrder.new(car: @car)

    set_meta_tags title: "#{@car.make} #{@car.model} #{@car.year} for Sale",
                description: "Find the best deals for #{@car.make} #{@car.model}!
                Stay updated with the hottest car shows and auto exhibitions! 🚘 AutoBidHub brings you exclusive coverage of classic car meets, luxury auto expos, and the latest vehicle showcases.",
                keywords: "cars, #{@car.make}, #{@car.model}, auto"
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def set_car
    @car = Car.friendly.find(params[:id])
  end

  def car_order_params
    params.require(:car_order).permit(:name, :email, :phone, :location, :quantity, :total_price)
  end

  # Helper method to check if filter parameters are present
  def filter_params_present?
    params[:make].present? || params[:model].present? || params[:steering].present? ||
      params[:min_price].present? || params[:max_price].present? || params[:year].present?
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/edit.html.erb
<h1>Cars#edit</h1>
<p>Find me in app/views/cars/edit.html.erb</p>

app/views/cars/index.html.erb
<% content_for :title, "Cars for Sale - New & Used Vehicles at AutoBidHub" %>
<% content_for :meta_description, "Browse a huge selection of new and used cars for sale. Find sedans, SUVs, trucks, and luxury cars at unbeatable prices. Compare models and get the best deals today!" %>
<% content_for :meta_keywords, "cars for sale, used cars, new cars, buy cars online, car dealership, SUVs, sedans, trucks, luxury cars, affordable cars" %>

<% content_for :meta_og_title, "Cars for Sale - Best Deals on New & Used Vehicles" %>
<% content_for :meta_og_description, "Find your dream car! Explore new and used cars, including sedans, SUVs, and luxury vehicles. Get the best deals on high-quality cars today!" %>
<% content_for :meta_og_image, "https://res.cloudinary.com/drxr1eiwp/image/upload/v1735674486/2018-Mazda-CX-5-20-Dynamic-Auto_1_yoittd.avif" %>

<div class="content-wrapper">
  <div class="makes-section">
    <%= render "shared/filter_form" %>

  </div>
  <div class="main-content">
  <h3>Cars For Sale (New and Used)</h3>
  <div id="car-list">
    <% @paginated_items.each do |car| %>
      <a href="<%= car_path(car) %>" class="card">
        <% if car.photos.present? %>
          <%= image_tag car.photos.first, alt: car.make, class: "car-image" %>
        <% else %>
          <div class="no-photo">No photo available</div>
        <% end %>
        <div class="card-info">
          <h4><%= car.make %> <%= car.model %> <%= car.year %></h4>
        <p>
          <i class="fas fa-tachometer-alt"></i>
          Millage: <%= car.chassis_no %> Mi
        </p>
        <p class="price">Price: $<%= car.price %></p>
      </div>
        </a>
      <% end %>
    </div>
  </div>
</div>
<div class="pagination-container">
  <%= paginate @paginated_items %>
</div>

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<p>Find me in app/views/cars/new.html.erb</p>

app/views/cars/show.html.erb
<div class="bike-contain" data-controller="showcars">
  <div class="bike-main-content">
    <div class="bike-main-image">
      <% content_for :title, "#{@car.make} #{@car.model} #{@car.year} for Sale | Latest Auto Exhibitions" %>
      <% content_for :meta_description, @car.description.truncate(156) %>
      <% content_for :meta_keywords, "Used cars for sale, #{@car.make} #{@car.model} #{@car.year}, used #{@car.make} #{@car.model} #{@car.year}, new #{@car.make} #{@car.model} #{@car.year}, buy #{@car.make} #{@car.model} #{@car.year} car, performance car" %>

      <% content_for :meta_og_title, "#{@car.make} #{@car.model} #{@car.year} for Sale - Best Deals on #{@car.make} #{@car.model} #{@car.year}" %>
      <% content_for :meta_og_description, @car.description.truncate(156) %>
      <% content_for :meta_og_image, cl_image_path(@car.photos.first.key) %>

      <% if @car.photos.attached? %>
        <% @car.photos.each_with_index do |photo, index| %>
          <div class="mySlides" data-showcars-target="slide" style="<%= index == 0 ? '' : 'display:none;' %>">
            <div class="numbertext">
              <i class="fa-solid fa-camera"></i> <%= index + 1 %>/<%= @car.photos.count %>
            </div>
            <%= cl_image_tag photo.key, alt: "#{@car.make} #{@car.model} #{@car.year}", class: "main-image" %>
          </div>
        <% end %>
      <% end %>

      <!-- Navigation Buttons -->
      <div class="slider-nav">
        <a class="prev" data-action="click->showcars#prev">❮</a>
        <a class="next" data-action="click->showcars#next">❯</a>
      </div>

      <!-- Saved Bikes Section -->
      <div class="saved-bike">
      <% if user_signed_in? %>
        <% saved = current_user.saved_cars.exists?(car: @car) %>

        <%= button_to car_saved_cars_path(@car),  # Make sure it's plural!
                    method: saved ? :delete : :post,
                    remote: true,
                    class: "btn favorite-btn",
                    data: { id: @car.id } do %>
          <i class="<%= saved ? 'fa-solid fa-heart' : 'fa-regular fa-heart' %>"
            style="<%= saved ? 'color: red;' : '' %>"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "btn" do %>
          <i class="fa-regular fa-heart"></i>
        <% end %>
      <% end %>
    </div>

      <!-- Bike Gallery -->
      <div class="bike-gallery">
        <% if @car.photos.attached? %>
          <div class="thumbnails">
            <% @car.photos.each_with_index do |photo, index| %>
              <% next if index == 0 %><!-- Skip the first image -->
              <%= cl_image_tag photo.key,
                height: 100, width: 100, crop: :fill,
                class: "thumbnail",
                alt: "#{@car.make} #{@car.model} #{@car.year}",
                data: { showcarsTarget: "thumbnail", action: "click->showcars#selectSlide", index: index + 1 } %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>




  <!-- Order Form Section -->
  <div class="bike-form">
    <%= simple_form_for [@car, @order],
      local: true,
      data: { controller: "loading", action: "submit->loading#showSpinner" },
      html: { class: "custom-bike-form" } do |form| %>
      <div class="row m-4">
        <h2 style="font-family: 'Montserrat', sans-serif"><%= "#{@car.make} #{@car.model} #{@car.year} For Sale" %></h2>
        <h2 style="color: red; font-size: 1.0rem;"><%= number_to_currency(@car.price) %></h2>
      </div>
      <% if @order.errors.any? %>
        <div class="error-messages alert alert-danger">
          <h3>There were some errors with your order:</h3>
          <ul>
            <% @order.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group m-4">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group m-4">
        <%= form.label :email %>
        <%= form.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group m-4">
        <%= form.label :phone %>
        <%= form.number_field :phone, class: "form-control" %>
      </div>

      <div class="form-group m-4">
        <%= form.label :location %>
        <%= form.text_field :location, class: "form-control" %>
      </div>

      <div class="form-group submit-button m-4">
        <%= form.button :submit, "GET A PRICE QUOTE", class: "btn btn-dark text-white" %>
      </div>
          <!-- Hidden honeypot field (bots will try to fill this, humans won't) -->
      <%= form.hidden_field :extra_info, value: "", autocomplete: "off" %>
      <span class="loader text-center" data-loading-target="spinner" style="display: none;"></span>
    <% end %>
  </div>
</div>

<!-- Bike Information Section -->
<div class="bike-details">
  <div class="popularity-stats">
    <h2 class="stats-title"><i class="fa-solid fa-phone" style="color: green;"></i> Contact the Dealer (341)223-3974</h2>
    <div class="stats-row">
      <div class="stats-item">
        <i class="fa-solid fa-eye"></i>
        <span><strong>Seen:</strong> <%= rand(30..100) %> times (last 30 days)</span>
      </div>
      <div class="stats-item">
        <i class="fa-solid fa-bookmark"></i>
        <span><strong>Saved:</strong> by <%= rand(2..10) %> people</span>
      </div>
      <div class="stats-item">
        <i class="fa-solid fa-tags"></i>
        <span><strong>Price Update:</strong> The price recently decreased by $<%= rand(1000..5000) %></span>
      </div>
    </div>
  </div>

  <table class="mt-5">
    <tr>
      <td><strong>Condition:</strong></td>
      <td><%= @car.condition %><strong></strong></td>
    <tr>
    <tr>
      <td><strong>Category:</strong></td>
      <td><i class="fa-solid fa-car-rear"></i> <%= @car.category %></td>
    </tr>
    <tr>
      <td><strong>Make:</strong></td>
      <td><%= @car.make %></td>
    </tr>
    <tr>
      <td><strong>Model:</strong></td>
      <td><i class="fa-solid fa-calendar"></i> <%= "#{@car.make} #{@car.model} #{@car.year}" %> </td>
    </tr>
    <tr>
      <td><strong>Milleage:</strong></td>
      <td><i class="fa-solid fa-gauge-high"></i> <%= @car.chassis_no %> km</td>
    </tr>
    <tr>
      <td><strong>Colour:</strong></td>
      <td><i class="fa-solid fa-droplet"></i> <%= @car.ext_color %></td>
    </tr>
    <tr>
      <td><strong>Engine Capacity:</strong></td>
      <td><i class="fa-solid fa-flag-checkered"></i> <%= @car.engine_size %> cc</td>
    </tr>
    <tr>
      <td><strong>Transmission:</strong></td>
      <td><%= @car.transmission%></td>
    </tr>
    <tr>
      <td><strong>Number of seats:</strong></td>
      <td><i class="fa-solid fa-car-burst"></i> <%= @car.seats %><strong></strong></td>
    <tr>
      <td><strong>Fuel:</strong></td>
      <td><i class="fa-solid fa-gas-pump"></i> <%= @car.fuel_type %></td>
    </tr>
    <tr>
      <td><strong>Description:</strong></td>
      <td><%= @car.description %></td>
    </tr>
  </table>
  <div class="actions">
    <%= link_to "Explore More Cars", cars_path, class: "primary-btn" %>
  </div>
<div>
  <%= link_to cars_path, class: "back-link" do %>
    <i class="fas fa-arrow-left"></i> Back to Cars
  <% end %>

  <% if current_user&.admin? %>
  <%= link_to edit_car_path(@car), class: "back-link" do %>
    <i class="fas fa-edit"></i> Edit Car
  <% end %>

  <%= button_to car_path(@car), method: :delete, data: { confirm: 'Are you sure?' }, class: "back-link" do %>
    <i class="fas fa-trash-alt"></i> Delete
  <% end %>
<% end %>

</div>
</div>
</div>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>